### ISSUE TITLE
Interaction with items?

### ISSUE THREAD

**Issue by Maradaehne** [MaterialDesignInXAML/MotionList#2]
Hello,

I really liked this motion list example. So I tried it in an application where the items should be able to react on user inputs like click or write something in a textbox. The problem I am running into is that when i click on the item it starts the animation and i can drag it around, but I cannot click for example a button in this item. Is there a way to achieve this?

best regards

**Comment by ButchersBoy** [comment]
Yes, it is possible.  I don't have the time to knock up a demo now, but I can point you in the right direction.  You need to specify a custom ``` Thumb ``` and mark it with ```  dragablz:DragablzItem.IsCustomThumb="True" ```.  Then only this part will be drag-able.  

A demo aimed at a standard tab control will help you:

https://github.com/ButchersBoy/Dragablz/blob/master/DragablzDemo/CustomHeader.xaml

**Comment by Maradaehne** [comment]
Great Advice. Easier than I thought. Thanks a lot.
